#Parametros Conexion PostgreSQL
spring.datasource.url=jdbc:postgresql://xxxxx:5432/xxxxx
spring.sql.init.encoding=UTF-8
spring.datasource.username=xxxx
spring.datasource.password=xxxx
# spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none